# taken from https://github.com/helix-editor/helix/blob/master/languages.toml#L2063
# and adding `goal` files to the list
[[language]]
name = "git-commit"
file-types = [
  { glob = "COMMIT_EDITMSG" },
  { glob = "MERGE_MSG" },
  { glob = "TAG_EDITMSG" },
  { glob = "**/.goals/[0-9][^.]*" }
]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
rulers = [51, 73]
text-width = 72
grammar = "gitcommit"
language-servers = [ "commit-lsp" ]

[[language]]
name = "markdown"
soft-wrap = { enable = true }

[[language]]
name = "text"
scope = "source.txt"
soft-wrap = { enable = true }
file-types = ["txt"]

[language-server.intelephense]
command = "intelephense"
args = ["--stdio"]

[language-server.intelephense.config.intelephense]
files.maxSize = 5000000
# Make sure these files aren't excluded:
# files.exclude = [
#     "**/vendor/**/{Tests,tests}/**",
#     "**/.git/**"
# ]
# NOT excluding _ide_helper.php
stubs = [
    "Core",
    "standard",
    "json",
    "mbstring",
    "pcre",
    "PDO",
    "mysqli",
    "curl",
    "openssl",
    "bcmath",
    "date",
    "hash",
    "filter",
    "session",
    "tokenizer",
    "xml",
    "laravel"
]
